# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'FearlessVideoFilter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 5.1'
    pod 'SDWebImage', '~> 5.0'
    pod 'SnapKit', '~> 5.0.0'

  target 'FearlessVideoFilterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FearlessVideoFilterUITests' do
    # Pods for testing
  end

end
